(() => {
  const btn = document.getElementById('sel-go');
  const stage = document.getElementById('sel-stage');
  const count = document.getElementById('sel-count');
  const sourcesEl = document.getElementById('sel-sources');
  const genresEl = document.getElementById('sel-genres');
  const genresWrap = document.getElementById('sel-genres-wrap');
  const modesEl = document.getElementById('sel-modes');
  const GEM_MIN_VIEWS = 3000;
  const burst = document.getElementById('sel-burst');
  if (!btn || !stage) return;

  let all = [];
  let pool = [];
  const recent = [];
  const activeSources = new Set();
  const activeGenres = new Set();
  const UNTAGGED = ' untagged';

  // How the pool is narrowed before the random pick. "deep" exists so the long
  // tail of artists gets played too, not just whatever already has an audience.
  // Name is the hook, note says plainly what you will actually get back.
  const MODES = [
    ['All', 'any', ''],
    ['Popular', 'popular', 'the most-watched sets'],
    ['Hidden gems', 'gems', 'underrated sets'],
    ['Niche sets', 'deep', 'hear them first']
  ];
  let mode = 'popular';

  const reduceMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  let sourceLogos = {};
  try { sourceLogos = JSON.parse(document.getElementById('sel-source-logos').textContent) || {}; } catch {}
  // One colour per channel, generated by scripts/channel-colors.py: taken from
  // the logo where the logo has one, and a spread-out tint where it is a
  // black-and-white wordmark. Applied per chip rather than as CSS rules so a
  // new channel is coloured the moment it appears, with no stylesheet to edit.
  let sourceColors = {};
  try { sourceColors = JSON.parse(document.getElementById('sel-source-colors').textContent) || {}; } catch {}

  const setButton = (label, state, disabled) => {
    btn.textContent = label;
    btn.dataset.state = state;
    btn.disabled = !!disabled;
  };
  const fmtDuration = s => {
    if (!s) return '';
    let m = Math.round(s / 60);
    const h = Math.floor(m / 60);
    m -= h * 60;
    return h ? `${h}h ${m}m` : `${m}m`;
  };
  const fmtCount = n => (n == null ? '' : n >= 1e6 ? `${(n / 1e6).toFixed(1)}M` : n >= 1e3 ? `${Math.round(n / 1e3)}K` : String(n));
  const escapeText = v => { const d = document.createElement('div'); d.textContent = v == null ? '' : String(v); return d.innerHTML; };
  const escapeAttr = v => escapeText(v).replace(/"/g, '&quot;');

  const render = item => {
    const name = item.artist || item.broadcaster;
    const label = item.title || (item.artist ? `${item.artist} · ${item.broadcaster}` : item.broadcaster);
    // show every genre tag, leading with the one the pool was filtered by
    const gs = item.genres || [];
    const matched = gs.find(x => activeGenres.has(x));
    const genreList = matched ? [matched, ...gs.filter(x => x !== matched)] : gs;
    const facts = [
      item.year ? ['Year', String(item.year)] : null,
      item.seconds ? ['Length', fmtDuration(item.seconds)] : null,
      item.views != null ? ['Views', fmtCount(item.views)] : null
    ].filter(Boolean)
      .map(([k, v]) => `<span><b>${k}:</b> ${escapeText(v)}</span>`)
      .join('');
    const tags = [];
    if (item.artist) {
      const lg = sourceLogos[item.broadcaster];
      const img = lg ? `<img class="sel-chip-logo" src="${escapeAttr(lg)}" width="14" height="14" alt="" loading="lazy" decoding="async">` : '';
      tags.push(`<span class="sel-tag-source" data-value="${escapeAttr(item.broadcaster)}">${img}${escapeText(item.broadcaster)}</span>`);
    }
    for (const g of genreList) tags.push(`<span class="sel-tag-genre">${escapeText(g)}</span>`);
    stage.innerHTML = `
      <div class="sel-card">
        <div class="sel-video">
          <iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(item.id)}?rel=0&autoplay=1"
                  title="${escapeAttr(label)}" loading="lazy"
                  allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>
        </div>
        <p class="sel-artist">${escapeText(name)}</p>
        ${tags.length ? `<p class="sel-tags">${tags.join('')}</p>` : ''}
        ${facts ? `<p class="sel-facts">${facts}</p>` : ''}
        <p class="sel-links"><a href="https://www.youtube.com/watch?v=${encodeURIComponent(item.id)}" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></p>
      </div>`;
    try { history.replaceState(null, '', '#' + item.id); } catch {}
  };

  const rebuildPool = () => {
    let next = all;
    if (activeSources.size) next = next.filter(s => activeSources.has(s.broadcaster));
    if (activeGenres.size) {
      next = next.filter(s => {
        const g = s.genres || [];
        return g.some(x => activeGenres.has(x)) || (activeGenres.has(UNTAGGED) && g.length === 0);
      });
    }
    const third = list => list.slice(0, Math.max(1, Math.ceil(list.length / 3)));
    if (mode === 'gems') {
      // loved per view rather than most-watched: the sets that punch above
      // their audience. Needs a views floor or tiny uploads dominate.
      const scored = next.filter(s => s.likes != null && s.views >= GEM_MIN_VIEWS)
        .slice().sort((a, b) => (b.likes / b.views) - (a.likes / a.views));
      if (scored.length) next = third(scored);
    } else if (mode === 'deep') {
      // the quiet end of the catalogue, so the long tail of artists gets played
      const scored = next.filter(s => s.views != null).slice().sort((a, b) => a.views - b.views);
      if (scored.length) next = third(scored);
    } else if (mode === 'popular') {
      // "most-watched" taken literally, so the label, the chip note and the copy
      // all describe the same thing. The exact mirror of "deep".
      const scored = next.filter(s => s.views != null).slice().sort((a, b) => b.views - a.views);
      if (scored.length) next = third(scored);
    }
    pool = next;
    if (count) {
      const bits = [];
      if (activeSources.size === 1) bits.push([...activeSources][0]);
      else if (activeSources.size) bits.push(`${activeSources.size} sources`);
      if (activeGenres.size) bits.push([...activeGenres].map(g => (g === UNTAGGED ? 'untagged' : g)).join(' / '));
      const label = (MODES.find(m => m[1] === mode) || [])[0];
      if (mode !== 'any' && label) bits.push(label.toLowerCase());
      count.textContent = `${pool.length.toLocaleString('en-US')} sets${bits.length ? ' · ' + bits.join(' · ') : ''}`;
      count.hidden = false;
    }
    if (!pool.length) setButton('Nothing matches, widen the filter', 'empty', true);
    else if (btn.dataset.state !== 'ready') setButton(recent.length ? 'Pick another' : 'Pick me a set', 'ready', false);
  };

  const SPARK_COLORS = ['var(--acid)', 'var(--cyan)', 'var(--yellow)', 'var(--coral)', 'var(--ink)'];
  const SPARKS = 12;
  const salute = () => {
    if (!burst) return;
    burst.textContent = '';
    for (let i = 0; i < SPARKS; i += 1) {
      const s = document.createElement('span');
      s.className = 'sel-spark';
      const angle = (Math.PI * 2 * i) / SPARKS + (Math.random() - 0.5) * 0.5;
      const dist = 46 + Math.random() * 50;
      s.style.setProperty('--tx', `${(Math.cos(angle) * dist).toFixed(1)}px`);
      s.style.setProperty('--ty', `${(Math.sin(angle) * dist - dist * 0.35).toFixed(1)}px`);   // bias the spray upward
      s.style.setProperty('--rot', `${((Math.random() * 2 - 1) * 220).toFixed(0)}deg`);
      s.style.setProperty('--c', SPARK_COLORS[i % SPARK_COLORS.length]);
      s.style.animationDelay = `${(Math.random() * 40).toFixed(0)}ms`;
      burst.appendChild(s);
    }
    setTimeout(() => { burst.textContent = ''; }, 660);
  };

  const pick = () => {
    if (!pool.length) return null;
    for (let i = 0; i < 12; i += 1) {
      const item = pool[Math.floor(Math.random() * pool.length)];
      if (pool.length <= recent.length || !recent.includes(item.id)) {
        recent.push(item.id);
        if (recent.length > 15) recent.shift();
        return item;
      }
    }
    return pool[Math.floor(Math.random() * pool.length)];
  };

  const go = () => {
    const item = pick();
    if (!item) return;
    if (!reduceMotion) {
      btn.dataset.spinning = 'true';
      setTimeout(() => { delete btn.dataset.spinning; }, 300);
      salute();
    }
    render(item);
    setButton('Pick another', 'ready', false);
  };
  btn.addEventListener('click', go);

  // Mode is one-of-four, unlike Source and Genre which are multi-select. So it is
  // a radio group, not a row of independent toggles: role="radio"/aria-checked,
  // a single tab stop, and arrow keys to move between the options.
  function buildModeChips() {
    if (!modesEl) return;
    modesEl.textContent = '';
    const chips = MODES.map(([label, value, note]) => {
      const b = document.createElement('button');
      b.type = 'button';
      b.className = 'sel-chip';
      b.setAttribute('role', 'radio');
      b.dataset.value = value;
      b.setAttribute('aria-checked', value === mode ? 'true' : 'false');
      b.tabIndex = value === mode ? 0 : -1;
      // the unfiltered option states the real size of the catalogue
      const line = value === 'any' ? `all ${all.length.toLocaleString('en-US')} sets` : note;
      b.innerHTML = `<span class="sel-chip-name">${escapeText(label)}</span>${
        line ? `<span class="sel-chip-note">${escapeText(line)}</span>` : ''}`;
      modesEl.appendChild(b);
      return b;
    });
    const select = (chip, focus) => {
      mode = chip.dataset.value;
      chips.forEach(x => {
        const on = x === chip;
        x.setAttribute('aria-checked', on ? 'true' : 'false');
        x.tabIndex = on ? 0 : -1;
      });
      if (focus) chip.focus();
      rebuildPool();
    };
    const STEP = { ArrowRight: 1, ArrowDown: 1, ArrowLeft: -1, ArrowUp: -1 };
    chips.forEach((c, i) => {
      c.addEventListener('click', () => select(c));
      c.addEventListener('keydown', e => {
        if (e.key === 'Home' || e.key === 'End') {
          e.preventDefault();
          select(chips[e.key === 'Home' ? 0 : chips.length - 1], true);
          return;
        }
        const step = STEP[e.key];
        if (!step) return;
        e.preventDefault();
        select(chips[(i + step + chips.length) % chips.length], true);
      });
    });
  }

  function makeChips(container, entries, activeSet, iconFor, paintFor) {
    if (!container) return;
    container.textContent = '';
    // name and count are separate so narrow screens can drop the count and fit
    // more chips per row
    const chip = (name, value, pressed, n) => {
      const b = document.createElement('button');
      b.type = 'button';
      b.className = 'sel-chip';
      b.dataset.value = value;
      b.setAttribute('aria-pressed', pressed ? 'true' : 'false');
      const tint = paintFor && paintFor(value);
      if (tint) {
        b.style.setProperty('--chip-on-bg', tint.bg);
        b.style.setProperty('--chip-on-fg', tint.fg);
        b.style.setProperty('--chip-hover', tint.bg);
        b.style.setProperty('--chip-hover-fg', tint.fg);
      }
      const icon = iconFor ? iconFor(value) : '';
      b.innerHTML = `${icon}<span class="sel-chip-name">${escapeText(name)}</span>${
        n == null ? '' : `<span class="sel-chip-n">(${escapeText(n)})</span>`}`;
      container.appendChild(b);
      return b;
    };
    const allChip = chip('All', '', !activeSet.size);
    const chips = entries.map(([name, value, n]) => chip(name, value, activeSet.has(value), n));
    const sync = () => {
      allChip.setAttribute('aria-pressed', activeSet.size ? 'false' : 'true');
      chips.forEach(c => c.setAttribute('aria-pressed', activeSet.has(c.dataset.value) ? 'true' : 'false'));
      rebuildPool();
    };
    allChip.addEventListener('click', () => { activeSet.clear(); sync(); });
    chips.forEach(c => c.addEventListener('click', () => {
      const v = c.dataset.value;
      if (activeSet.has(v)) activeSet.delete(v); else activeSet.add(v);
      sync();
    }));
  }

  function buildFilters() {
    const srcCounts = new Map();
    const genCounts = new Map();
    let untaggedCount = 0;
    for (const s of all) {
      srcCounts.set(s.broadcaster, (srcCounts.get(s.broadcaster) || 0) + 1);
      const g = s.genres || [];
      if (!g.length) untaggedCount += 1;
      for (const x of g) genCounts.set(x, (genCounts.get(x) || 0) + 1);
    }
    const sourceIcon = value => {
      const src = sourceLogos[value];
      return src ? `<img class="sel-chip-logo" src="${escapeAttr(src)}" width="18" height="18" alt="" loading="lazy" decoding="async">` : '';
    };
    makeChips(sourcesEl,
      [...srcCounts.keys()].sort((a, b) => a.localeCompare(b)).map(n => [n, n, srcCounts.get(n)]),
      activeSources, sourceIcon, value => sourceColors[value] || null);
    const ranked = [...genCounts.entries()].filter(([, n]) => n >= 10).sort((a, b) => b[1] - a[1]);
    if (ranked.length) {
      const genres = ranked.slice(0, 18).map(([g, n]) => [g, g, n]);
      if (untaggedCount) genres.push(['untagged', UNTAGGED]);
      makeChips(genresEl, genres, activeGenres);
      if (genresWrap) genresWrap.hidden = false;
    }
    if (all.some(s => s.likes != null)) buildModeChips();
  }

  // selector-data.min.json is the compact build of selector-data.json: names
  // interned into lookup tables, one tuple per set. Half the bytes to download
  // and parse; expanded back into plain objects here so nothing downstream has
  // to know about the packing.
  const expand = data => {
    if (Array.isArray(data)) return data.filter(s => s && s.id);
    if (!data || !Array.isArray(data.s)) return [];
    const b = data.b || [], g = data.g || [];
    return data.s.map(([id, artist, bi, year, seconds, views, likes, gi]) => {
      const set = { id, artist, broadcaster: b[bi], year: year || null,
                    seconds, views, likes: likes === -1 ? null : likes };
      if (gi && gi.length) set.genres = gi.map(i => g[i]);
      return set;
    }).filter(s => s && s.id);
  };

  fetch('selector-data.min.json', { cache: 'no-cache' })
    .then(r => (r.ok ? r.json() : Promise.reject(new Error(r.status))))
    .then(data => {
      all = expand(data);
      if (!all.length) { setButton('Catalogue is still being built', 'empty', true); return; }
      buildFilters();
      rebuildPool();
      setButton('Pick me a set', 'ready', false);
      const hashId = decodeURIComponent((location.hash || '').replace(/^#/, ''));
      const fromHash = hashId && all.find(s => s.id === hashId);
      if (fromHash) { recent.push(fromHash.id); render(fromHash); setButton('Pick another', 'ready', false); }
    })
    .catch(() => setButton('Catalogue failed to load — reload the page', 'error', true));
})();
