// Hand-tagged artist -> genres, keyed by lowercased artist name. Curated from
// scene knowledge for the acts that recur most across the catalogue, so the
// genre filter has an accurate core. Automatic sources (title text, uploader
// keywords) fill in the rest; see scripts/apply-genres.mjs.
//
// Keep values inside the vocabulary in scripts/genre-vocab.mjs. 1-3 tags each,
// most characteristic first. Only add an act you are sure of.

export const MANUAL = {
  // --- house / deep / minimal ---------------------------------------------
  'move d': ['deep house', 'house'],
  'palms trax': ['house', 'deep house'],
  'shanti celeste': ['house', 'deep house'],
  'gene on earth': ['deep house', 'minimal'],
  'leon vynehall': ['house', 'deep house'],
  'cinthie': ['house', 'deep house'],
  'iron curtis': ['house', 'deep house'],
  'johannes albert': ['house'],
  'unai trotti': ['house'],
  'toribio': ['house'],
  'musclecars': ['deep house', 'house'],
  'gabrielle kwarteng': ['house'],
  'sally c': ['house'],
  'cormac': ['house'],
  'the carry nation': ['house'],
  'kim ann foxman': ['house', 'acid'],
  'dana ruh': ['deep house', 'house'],
  'demuja': ['house', 'deep house'],
  'fantastic man': ['house'],
  'dj seinfeld': ['house', 'deep house'],
  'baltra': ['house', 'deep house'],
  'ron like hell': ['house', 'ebm'],
  'paramida': ['house'],
  'alex kassian': ['deep house', 'ambient'],
  'shubostar': ['house', 'italo disco'],
  'budino': ['house', 'italo disco'],
  'dc salas': ['house', 'italo disco'],
  'jennifer cardini': ['house', 'italo disco'],

  // --- techno ------------------------------------------------------------
  'marcel fengler': ['techno'],
  'setaoc mass': ['techno'],
  'amotik': ['techno'],
  'antigone': ['techno'],
  'z.i.p.p.o': ['techno'],
  'etapp kyle': ['techno'],
  'quelza': ['techno'],
  'elad magdasi': ['techno'],
  'narciss': ['techno'],
  'julia govor': ['techno'],
  'nastia': ['techno', 'house'],
  'radio slave': ['techno', 'house'],
  'daniel avery': ['techno'],
  'ellen allien': ['techno'],
  'fiedel': ['techno', 'electro'],
  'alan oldham': ['techno', 'electro'],
  'dasha rush': ['techno', 'ambient'],
  'eric cloutier': ['hypnotic techno', 'techno'],
  'polygonia': ['hypnotic techno', 'techno'],
  'konduku': ['hypnotic techno', 'techno'],
  'decka': ['techno', 'hypnotic techno'],
  're:ni': ['techno', 'trance'],
  'reka': ['techno', 'ebm'],
  'ryan elliott': ['techno', 'house'],
  'ryan james ford': ['electro', 'techno'],

  // --- hard / industrial techno ----------------------------------------
  'spfdj': ['hard techno', 'techno'],
  'rebekah': ['hard techno', 'techno'],
  'sarah wild': ['hard techno', 'techno'],
  'daria kolosova': ['hard techno', 'techno'],
  'cashu': ['hard techno', 'techno'],
  'henning baer': ['hard techno', 'techno'],
  'dustin zahn': ['techno', 'hard techno'],
  'fjaak': ['techno', 'hard techno'],
  'patrick mason': ['hard techno', 'techno'],
  'ancient methods': ['industrial', 'techno'],
  'phase fatale': ['industrial', 'techno'],
  'p.e.a.r.l.': ['industrial', 'techno'],
  'kamikaze space programme': ['techno', 'industrial'],
  'the brvtalist': ['industrial', 'techno'],
  'max durante': ['industrial', 'techno', 'ebm'],
  'unhuman': ['hard techno', 'industrial', 'trance'],
  'stella zekri': ['hard techno', 'trance'],
  'vtss': ['hard techno', 'electro'],
  'cera khin': ['hard techno', 'hardcore'],
  'dj mell g': ['trance', 'hardcore'],

  // --- electro --------------------------------------------------------
  'luz1e': ['electro'],
  'solid blake': ['electro', 'techno'],
  'd.dan': ['techno', 'electro'],
  'reptant': ['electro', 'acid'],
  'sepehr': ['electro', 'acid', 'techno'],
  'maruwa': ['electro', 'trance', 'breakbeat'],
  'ok williams': ['techno', 'electro', 'breakbeat'],
  'mor elian': ['electro', 'techno', 'breakbeat'],
  'jadalareign': ['techno', 'electro'],
  'boys noize': ['electro', 'techno'],
  'martyn bootyspoon': ['electro', 'ghetto house'],
  'sedef adasi': ['electro', 'techno'],
  'u.r.trax': ['trance', 'electro'],
  'ferrari rot': ['ebm', 'electro'],

  // --- acid ----------------------------------------------------------
  'dr. rubinstein': ['acid', 'techno'],
  'alien rain': ['acid', 'techno'],
  'volvox': ['techno', 'acid'],
  'x-coast': ['electro', 'breakbeat', 'acid'],

  // --- ebm / wave / dark disco ------------------------------------------
  'pablo bozzi': ['ebm', 'italo disco', 'electro'],
  'identified patient': ['ebm', 'electro'],
  'kris baha': ['ebm', 'italo disco'],
  'curses': ['ebm', 'italo disco'],
  'alessandro adriani': ['ebm', 'industrial', 'new wave'],
  'zanias': ['ebm', 'industrial'],
  'marlon hoffstadt': ['house', 'hard techno', 'trance'],
  'younger than me': ['italo disco', 'new wave'],

  // --- trance ------------------------------------------------------------
  'ki/ki': ['trance', 'hard techno'],
  'courtesy': ['trance', 'techno'],
  'violet': ['trance', 'techno'],
  'gigi fm': ['trance', 'ambient'],
  'dj gigola': ['trance', 'hard techno'],
  'octo octa': ['house', 'breakbeat', 'trance'],

  // --- breakbeat / bass / uk garage -----------------------------------
  'anz': ['house', 'uk garage', 'breakbeat'],
  'roza terenzi': ['house', 'breakbeat', 'electro'],
  'ciel': ['house', 'techno', 'breakbeat'],
  'haai': ['techno', 'breakbeat'],
  'interplanetary criminal': ['uk garage', 'bassline'],
  'conducta': ['uk garage', '2-step', 'bassline'],
  'main phase': ['uk garage', 'bassline'],
  'amy dabbs': ['uk garage', 'house', 'breakbeat'],
  'bakey': ['uk garage', 'uk bass'],
  'mia koden': ['uk garage', '2-step'],
  'eliza rose': ['house', 'uk garage'],
  'yung singh': ['uk garage', 'bassline'],
  'roska': ['uk garage', 'uk bass'],
  'oneman': ['uk garage', 'grime', 'uk bass'],
  'faltydl': ['uk garage', 'idm', '2-step'],
  'bok bok': ['grime', 'uk bass'],
  'nikki nair': ['uk bass', 'electro', 'breakbeat'],
  'hodge': ['uk bass', 'techno', 'dubstep'],
  'tsvi': ['uk bass'],
  'dj plead': ['uk bass'],
  'jossy mitsu': ['uk bass', 'footwork'],
  'privacy': ['uk garage', 'uk bass'],
  'amelia holt': ['uk garage', 'house'],

  // --- dubstep / grime -------------------------------------------------
  'skream': ['dubstep', 'uk garage'],
  'pinch': ['dubstep', 'uk bass'],
  'martyn': ['dubstep', 'uk bass', 'techno'],
  'madam x': ['uk bass', 'grime'],
  'oblig': ['grime', 'dubstep'],
  'logan sama': ['grime'],
  'slimzee': ['grime', 'uk garage'],
  'elijah': ['grime'],
  'd double e': ['grime'],
  'flowdan': ['grime'],
  'novelist': ['grime'],
  'sir spyro': ['dubstep', 'grime', 'uk garage'],
  'amaliah': ['dubstep', 'uk bass'],

  // --- jungle / drum and bass ---------------------------------------
  'tim reaper': ['jungle', 'drum and bass'],
  'nia archives': ['jungle', 'drum and bass'],
  'mantra': ['jungle', 'drum and bass'],
  'om unit': ['jungle', 'drum and bass', 'dub'],
  'goldie': ['drum and bass', 'jungle'],
  'dj storm': ['drum and bass', 'jungle'],
  'kloke': ['drum and bass'],
  'london elektricity': ['drum and bass'],

  // --- footwork / club ------------------------------------------------
  'kush jones': ['footwork', 'juke', 'jungle'],
  'dj swisha': ['footwork', 'jersey club', 'techno'],
  'jwords': ['jersey club', 'electro'],
  'moma ready': ['house', 'techno', 'jungle'],
  'acemo': ['house', 'techno'],
  'lsdxoxo': ['jersey club', 'ghetto house'],
  'dj haram': ['jersey club'],
  'bambii': ['dancehall', 'jersey club', 'jungle'],
  'mcr-t': ['ghetto house', 'electro', 'hard techno'],
  'dj fuckoff': ['house', 'hard techno', 'ghetto house'],
  'teki latex': ['uk bass', 'jersey club'],
  'jubilee': ['electro', 'jersey club'],

  // --- gqom / singeli / global club ---------------------------------
  'dj lag': ['gqom'],
  'dj travella': ['singeli'],
  'nick león': ['dembow', 'reggaeton'],
  'dj python': ['downtempo', 'dembow', 'ambient'],
  'verraco': ['techno', 'uk bass'],

  // --- dub techno / deep --------------------------------------------
  'purelink': ['ambient', 'dub techno', 'downtempo'],
  'xdb': ['deep house', 'dub techno'],
  'priori': ['deep house', 'electro', 'dub techno'],
  'dj pete': ['dub techno', 'techno'],

  // --- downtempo / ambient / jazz ---------------------------------
  'laraaji': ['ambient'],
  'keith fullerton whitman': ['experimental', 'ambient'],
  'nicola cruz': ['downtempo', 'deep house'],
  'gilles peterson': ['jazz'],
  'shigeto': ['hip-hop', 'idm'],
  'quantic': ['funk', 'disco'],
  'jessy lanza': ['r&b', 'synth-pop'],
  'perel': ['synth-pop', 'italo disco', 'house'],

  // --- collectives that read as one act --------------------------------
  'black rave culture': ['house', 'techno', 'breakbeat'],

  // --- manual pass, batch 2 (top recurring acts in the catalogue) ------
  'marcel dettmann': ['techno', 'hard techno'],
  'carl craig': ['techno'],
  'a guy called gerald': ['acid', 'jungle', 'techno'],
  'dj stingray': ['electro', 'techno'],
  'objekt': ['electro', 'idm', 'techno'],
  'machinedrum': ['footwork', 'jungle', 'drum and bass'],
  'actress': ['experimental', 'techno'],
  'rødhåd': ['techno'],
  'héctor oaks': ['hard techno', 'techno', 'ebm'],
  'scuba': ['dubstep', 'techno', 'uk bass'],
  'mall grab': ['house', 'breakbeat'],
  'horse meat disco': ['disco', 'nu-disco'],
  'louie vega': ['house', 'deep house'],
  'fabio': ['drum and bass', 'jungle'],
  'grooverider': ['drum and bass', 'jungle'],
  'fabio & grooverider': ['drum and bass', 'jungle'],
  'jamie jones': ['tech house', 'house'],
  'job jobse': ['house', 'techno', 'trance'],
  'james blake': ['r&b', 'dubstep'],
  'sherelle': ['footwork', 'jungle', 'drum and bass'],
  'nkisi': ['hardcore', 'gabber', 'industrial'],
  'nur jaber': ['hard techno', 'industrial'],
  'dj boring': ['house', 'deep house'],
  'roman flügel': ['house', 'techno', 'electro'],
  'nabihah iqbal': ['new wave', 'synth-pop'],
  'bloody mary': ['deep house', 'techno'],
  'jus-ed': ['deep house', 'house'],
  'kornél kovács': ['house'],
  'fred p': ['deep house', 'house'],
  'george fitzgerald': ['house', 'uk garage'],
  'deadbeat': ['dub techno', 'dub'],
  'matrixxman': ['techno'],
  'inland': ['techno', 'hypnotic techno'],
  'salome': ['hard techno', 'hypnotic techno', 'techno'],
  'shonky': ['tech house', 'minimal', 'house'],
  'franz scala': ['italo disco', 'disco'],
  'fabrizio mammarella': ['italo disco', 'disco'],
  'jennifer touch': ['electro', 'synth-pop'],
  'milan hermess': ['electro'],
  'mejle': ['electro', 'techno'],
  'alex.do': ['techno'],
  'russell e. l. butler': ['techno', 'electro'],
  'juliana huxtable': ['industrial', 'techno'],
  'chloé lula': ['techno', 'ebm'],
  'chloé caillet': ['house', 'tech house'],
  'carista': ['house', 'uk garage'],
  'cromby': ['house', 'uk garage'],
  'kiernan laveaux': ['house', 'techno'],
  'kia': ['house', 'breakbeat'],
  'cinnaman': ['uk bass', 'breakbeat'],
  'ivan smagghe': ['electro', 'italo disco'],
  'prince language': ['disco', 'house'],
  'justin strauss': ['disco', 'house', 'new wave'],
  'eli escobar': ['house', 'disco'],
  'dj tennis': ['house', 'techno'],
  'damiano von erckert': ['house'],
  'auntie flo': ['house'],
  'young marco': ['house', 'downtempo'],
  'kutmah': ['hip-hop'],
  'goya gumbani': ['hip-hop'],
  'jarreau vandal': ['hip-hop', 'uk bass'],
  'zag': ['jazz', 'disco', 'funk'],
  'donna leake': ['jazz'],
  'lefto': ['hip-hop', 'jazz'],
  'lefto early bird': ['hip-hop', 'jazz'],
  'think outside the kiosk w lefto early bird': ['hip-hop', 'jazz'],
  'analog soul': ['deep house', 'house'],
  'kilopatrah jones': ['house', 'disco'],
  'juan maclean': ['house', 'disco', 'electro'],
  'the juan maclean': ['house', 'disco', 'electro'],
  'dj voices': ['techno', 'electro'],
  'takaya nagase': ['house', 'deep house'],
  'kfeelz': ['deep house', 'house'],
  'ben ufo': ['uk bass', 'techno', 'house'],
  'marcel fengler': ['techno', 'hard techno'],
  'baltra': ['house', 'deep house'],
  'iron curtis': ['house', 'deep house'],
  'beta librae': ['house', 'breakbeat'],
  'miley serious': ['electro', 'trance'],
  'mike servito': ['house', 'techno', 'acid'],
  'dr. dubplate': ['uk garage', 'dubstep', 'uk bass'],
  'riko dan': ['grime'],
  'jammz': ['grime'],
  'sp:mc': ['dubstep', 'drum and bass'],
  'grandmixxer': ['grime'],
  'the grime show: grandmixxer': ['grime'],
  'the grime show: logan sama': ['grime'],
  'the grime show: spooky': ['grime'],
  'addison groove': ['footwork', 'techno', 'juke'],
  'introspekt': ['uk garage', 'uk bass'],
  'i. jordan': ['uk bass', 'breakbeat', 'trance'],
  'nala brown': ['jungle', 'drum and bass'],
  'badsista': ['baile funk', 'jersey club'],
  'dinamarca': ['dembow', 'reggaeton'],
  'zombies in miami': ['italo disco', 'house', 'nu-disco'],
  'khidja': ['electro', 'italo disco'],
  'robert dietz': ['tech house', 'house'],
  'l.f.t.': ['electro', 'techno'],
  'interstellar funk': ['electro'],
  'acemoma': ['house', 'techno', 'jungle'],
  'i jordan': ['uk bass', 'breakbeat', 'trance'],
  'dj plead': ['uk bass'],
  'akanbi': ['afrobeats', 'amapiano', 'house'],

  // --- manual pass, batch 3 ------------------------------------------
  'jasss': ['techno', 'industrial', 'ebm'],
  'paul seul': ['hardcore', 'gabber'],
  'xiorro': ['techno'],
  'monty luke': ['house', 'techno'],
  'jamz supernova': ['uk bass'],
  'korea town acid': ['house', 'experimental'],
  'mcmlxxxv': ['synth-pop', 'italo disco', 'electro'],
  'red pig flower': ['techno'],
  'tijana t': ['techno'],
  'artwork': ['dubstep', 'uk garage'],
  'demi riquísimo': ['house', 'disco'],
  'matias aguayo': ['minimal', 'experimental'],
  'lúcia lu': ['progressive house', 'trance'],
  'djedjotronic': ['electro', 'techno'],
  'dubfire': ['techno', 'tech house'],
  'helena hauff': ['electro', 'acid', 'ebm'],
  'kink': ['house', 'acid', 'techno'],
  'kmru': ['ambient', 'experimental'],
  'lena willikens': ['ebm', 'new wave', 'experimental'],
  'locked groove': ['techno', 'house'],
  'jamie xx': ['house', 'uk bass'],
  'peggy gou': ['house', 'tech house'],
  'richie hawtin': ['minimal', 'techno'],
  'ben sims': ['techno', 'hard techno'],
  'surgeon': ['techno', 'industrial', 'hard techno'],
  'answer code request': ['techno'],
  'appleblim': ['dubstep', 'techno'],
  'prosumer': ['house', 'deep house'],
  'project pablo': ['house', 'deep house'],
  'randomer': ['techno', 'uk bass', 'electro'],
  'parris': ['uk bass', 'techno'],
  'ploy': ['uk bass', 'techno'],
  'riz la teef': ['dubstep', 'uk bass'],
  'sam binga': ['drum and bass', 'jungle', 'footwork'],
  'scratcha dva': ['grime', 'uk garage'],
  'titonton duvanté': ['deep house', 'techno'],
  'trends': ['grime', 'dubstep'],
  'umfang': ['techno'],
  'vigro deep': ['amapiano'],
  'habibi funk': ['funk', 'soul', 'disco'],
  'intergalactic gary': ['electro', 'ebm', 'new wave'],
  'last japan': ['grime', 'uk bass'],
  'salute': ['uk garage', 'breakbeat', 'uk bass'],
  'poly chain': ['electro', 'synth-pop'],
  'regularfantasy': ['house', 'uk garage'],
  'roi perez': ['house', 'disco'],
  'ariel zetina': ['techno', 'jersey club'],
  'batida': ['kuduro', 'afro house'],
  'adiel': ['techno'],
  'amine edge': ['house', 'tech house'],
  'bailey ibbs': ['uk garage', 'techno', 'uk bass'],
  'black loops': ['deep house', 'house'],
  'bianca oblivion': ['uk bass', 'dancehall'],

  // --- manual pass, batch 4 (targets the "Popular only" pool) ----------
  'dj hell': ['electro', 'ebm', 'techno'],
  'chaos in the cbd': ['deep house', 'house'],
  'bonobo': ['downtempo', 'experimental'],
  'call super': ['techno', 'experimental'],
  'shlømo': ['techno', 'hard techno'],
  'cem': ['hard techno', 'industrial', 'techno'],
  'raven': ['hard techno', 'techno'],
  'tornado wallace': ['house', 'downtempo'],
  'carl cox': ['techno', 'tech house'],
  'maceo plex': ['techno', 'house'],
  'hiroko yamamura': ['techno'],
  'laurent garnier': ['techno', 'house'],
  'nina kraviz': ['techno', 'acid'],
  'anetha': ['hard techno', 'techno', 'trance'],
  'kerri chandler': ['deep house', 'house'],
  'dj ez': ['uk garage', '2-step'],
  'jayda g': ['house', 'disco'],
  'kettama': ['house', 'uk garage'],
  'dj heartstring': ['trance', 'hard techno', 'house'],
  'inhalt der nacht': ['hard techno', 'techno'],
  'chlär': ['hard techno', 'techno'],
  'gabber modus operandi': ['gabber', 'hardcore', 'experimental'],
  'hitech': ['ghetto house', 'footwork'],
  'ian pooley': ['house', 'deep house'],
  'ron trent': ['deep house', 'house'],
  'dj pierre': ['acid', 'house'],
  'dj stingray 313': ['electro', 'techno'],
  'fadi mohem': ['techno'],
  'eats everything': ['house', 'tech house'],
  'dj godfather': ['ghetto house', 'footwork', 'juke'],
  'tom trago': ['house'],
  'sunil sharpe': ['hard techno', 'techno'],
  'claudio prc': ['hypnotic techno', 'dub techno', 'techno'],
  'clouds': ['techno', 'hardcore'],
  'shed': ['techno', 'dub techno'],
  'saoirse': ['house', 'breakbeat', 'trance'],
  'disclosure': ['house', 'uk garage'],
  'folamour': ['house', 'disco', 'funk'],
  'adam port': ['house', 'tech house'],
  'klangkuenstler': ['hard techno', 'techno'],
  'denis sulta': ['house', 'techno'],
  'tsha': ['house', 'breakbeat'],
  'maya jane coles': ['deep house', 'tech house'],
  'nic fanciulli': ['tech house', 'techno'],
  "barry can't swim": ['house', 'downtempo'],
  'regal': ['hard techno', 'acid', 'techno'],
  'dixon': ['deep house', 'house'],
  'mura masa': ['uk bass', 'hip-hop'],
  'major league djz': ['amapiano'],
  'mano le tough': ['house', 'deep house'],
  'manara': ['reggaeton', 'dancehall'],
  'the gaslamp killer': ['hip-hop', 'experimental'],
  'annē': ['hard techno', 'techno'],
  'alarico': ['hard techno', 'techno'],
  'alignment': ['hard techno', 'techno'],
  'tommy holohan': ['hard techno', 'techno'],
  'modeselektor': ['idm', 'breakbeat', 'experimental'],
  'x club.': ['hard techno', 'industrial', 'techno'],
  'dj marky': ['drum and bass', 'jungle'],
  'omar s': ['house', 'techno', 'deep house'],
  'blawan': ['techno', 'hard techno'],
  'shlohmo': ['hip-hop', 'experimental'],
  'claude vonstroke': ['tech house', 'house'],
  'neil landstrumm': ['techno', 'electro'],
  'chimpo': ['drum and bass', 'jungle'],
  'catz n dogz': ['house', 'tech house'],
  'obscure shape': ['hard techno', 'techno'],
  'ewan mcvicar': ['house', 'tech house'],
  'kevin saunderson': ['techno'],
  'function': ['techno'],
  'marie davidson': ['electro', 'ebm', 'synth-pop'],
  'neffa-t': ['uk garage', 'bassline', 'uk bass'],
  'karizma': ['house', 'baltimore club'],
  'dj koolt': ['minimal', 'tech house'],
  'dmx krew': ['electro', 'synth-pop'],
  'peach': ['house', 'breakbeat', 'trance'],
  'safety trance': ['dembow', 'reggaeton'],
  'busy p': ['house', 'electro'],
  'lenny dee': ['hardcore', 'gabber'],
  'dj spinna': ['hip-hop', 'house', 'soul'],
  'soul clap': ['house', 'disco'],
  'special request': ['jungle', 'breakbeat', 'hardcore'],
  'cardopusher': ['electro', 'techno'],
  'the hacker': ['electro', 'ebm', 'techno'],
  'lady starlight': ['techno', 'industrial'],
  'freddy k': ['techno', 'hard techno'],
  'danilo plessow': ['deep house', 'house'],
  'dbridge': ['drum and bass', 'jungle'],
  'daniele baldelli': ['disco', 'italo disco', 'nu-disco'],
  'waze': ['house', 'uk garage'],
  'uvb': ['hard techno', 'techno'],
  'truncate': ['techno'],
  'detroit in effect': ['electro', 'ghetto house'],
  'françois k': ['house', 'dub', 'disco'],
  'françois x': ['techno'],
  'rahaan': ['disco', 'house'],
  'dan ghenacia': ['minimal', 'tech house'],
  'jimmy edgar': ['electro', 'r&b', 'house'],
  'mikeq': ['jersey club'],
  'mad miran': ['house', 'breakbeat', 'electro'],
  'local suicide': ['italo disco', 'synth-pop'],
  'slam': ['techno'],
  'maayan nidam': ['minimal', 'house'],
  'cltx': ['hard techno', 'techno'],
  'camea': ['techno'],
  'justin jay': ['house', 'tech house'],
  'asquith': ['techno', 'acid', 'breakbeat'],
  'nikita zabelin': ['techno'],
  'dj hyperdrive': ['hard techno', 'gabber'],
  'nicole': ['techno', 'hard techno'],
  'baugruppe90': ['hard techno', 'trance'],
  'blazej malinowski': ['hypnotic techno', 'dub techno', 'techno'],
  'insolate': ['techno'],
  'david löhlein': ['hard techno', 'techno'],

  // --- manual pass, batch 5 (Popular-only pool, deeper) ---------------
  'jeremy underground': ['deep house', 'house'],
  'grace dahl': ['hard techno', 'techno'],
  'sicaria': ['dubstep', 'uk bass'],
  'hudson mohawke': ['hip-hop', 'experimental'],
  'perc': ['industrial', 'techno', 'hard techno'],
  'totally enormous extinct dinosaurs': ['house'],
  'derrick carter': ['house', 'deep house'],
  'todd edwards': ['uk garage', '2-step'],
  'a-trak': ['hip-hop', 'house'],
  'cc:disco!': ['disco', 'nu-disco'],
  'loefah': ['dubstep', 'grime'],
  'prospa': ['breakbeat', 'techno'],
  'john talabot': ['house', 'deep house'],
  'hadone': ['hard techno', 'techno'],
  'ryuichi sakamoto': ['ambient', 'experimental'],
  'red axes': ['electro', 'italo disco'],
  'just blaze': ['hip-hop'],
  'mark broom': ['techno'],
  'dan shake': ['house', 'disco'],
  'dense': ['techno'],
  'roy davis jr': ['house', 'uk garage', 'deep house'],
  'la fleur': ['house', 'techno'],
  'stanislav tolkachev': ['techno', 'hypnotic techno'],
  'goth-trad': ['dubstep'],
  'satoshi tomiie': ['house', 'deep house'],
  'wata igarashi': ['hypnotic techno', 'techno'],
  'craig richards': ['house', 'techno', 'minimal'],
  'dj q': ['bassline', 'uk garage'],
  'laurel halo': ['experimental', 'ambient'],
  'shifted': ['techno', 'industrial'],
  'lunice': ['hip-hop', 'experimental'],
  'midland': ['house', 'disco', 'breakbeat'],
  'kahn': ['dubstep', 'grime', 'uk bass'],
  'heidi': ['house', 'tech house'],
  'tommy four seven': ['techno', 'industrial'],
  'and': ['techno', 'industrial'],
  'amémé': ['afro house', 'house'],
  'kedr livanskiy': ['synth-pop', 'experimental'],
  'adriana lopez': ['hard techno', 'hypnotic techno', 'techno'],
  'dj bone': ['techno'],
  'nathan fake': ['idm', 'techno'],
  'wookie': ['uk garage', '2-step'],
  'tayhana': ['dembow', 'reggaeton'],
  'sofia kourtesis': ['house', 'downtempo'],
  'bambounou': ['techno', 'breakbeat'],
  'levon vincent': ['house', 'techno', 'deep house'],
  'pional': ['house'],
  'crystallmess': ['experimental', 'gqom'],
  'galcher lustwerk': ['deep house', 'house'],
  'nick höppner': ['house', 'techno'],
  'paranoid london': ['acid', 'house'],
  'tama sumo': ['house', 'deep house'],
  'black milk': ['hip-hop'],
  'anastasia kristensen': ['techno', 'electro'],
  'zed bias': ['uk garage', '2-step', 'bassline'],
  'umwelt': ['electro', 'techno'],
  'lns': ['electro', 'techno'],
  'robert owens': ['house', 'deep house'],
  'florian meindl': ['techno'],
  'aya': ['experimental', 'uk bass'],
  'samiyam': ['hip-hop', 'experimental'],
  'plastician': ['grime', 'dubstep'],
  'schacke': ['hard techno', 'trance', 'techno'],
  'speedy j': ['techno', 'electro'],
  'secretsundaze': ['house', 'deep house'],
  'dj firmeza': ['kuduro'],
  'voiski': ['techno', 'electro'],
  'krystal klear': ['house', 'disco'],
  'truss': ['techno', 'hard techno'],
  'champion': ['grime', 'uk bass', 'uk garage'],
  'fracture': ['jungle', 'footwork', 'drum and bass'],
  'cosmin trg': ['techno', 'uk bass'],
  'norman nodge': ['techno'],
  'parrish smith': ['ebm', 'industrial'],
  'exos': ['techno'],
  'boo williams': ['house', 'deep house'],
  'alexander kowalski': ['techno', 'electro'],
  'lucy': ['techno', 'experimental'],
  "sama' abdulhadi": ['techno'],
  'chase': ['drum and bass', 'jungle'],
  'honey dijon': ['house', 'disco', 'tech house'],
  'whomadewho': ['nu-disco', 'synth-pop'],
  'above': ['trance'],
  'skrillex': ['dubstep', 'uk bass'],
  'monolink': ['downtempo', 'house'],
  'nicolas jaar': ['experimental', 'downtempo'],
  'len faki': ['techno', 'hard techno'],
  'funk tribu': ['hard techno', 'techno'],
  'azyr': ['hard techno', 'techno'],
  'sven väth': ['techno', 'trance'],
  'txc': ['amapiano'],
  'sub focus': ['drum and bass'],
  'armand van helden': ['house', 'big beat'],
  'trym': ['hard techno', 'techno'],
  'frankie knuckles': ['house', 'deep house'],
  'nico moreno': ['hard techno', 'techno'],
  'overmono': ['uk bass', 'breakbeat', 'techno'],
  'shimza': ['afro house', 'tech house'],
  'arca': ['experimental'],
  'chris stussy': ['house', 'tech house', 'minimal'],
  'reinier zonneveld': ['techno', 'hard techno', 'acid'],

  // --- manual pass, batch 6 (Popular pool, 3-6 set tier) --------------
  'marie montexier': ['house', 'minimal'],
  'elli acula': ['techno', 'electro'],
  'marie lung': ['techno', 'electro'],
  'lea occhi': ['techno'],
  'lucinee': ['hypnotic techno', 'techno'],
  'the lady machine': ['electro', 'techno'],
  's ruston': ['techno'],
  'métaraph': ['techno', 'hard techno'],
  'charly schaller': ['techno'],
  'sept': ['hard techno', 'techno'],
  'estella boersma': ['hard techno', 'techno', 'electro'],
  'tomoki tamura': ['deep house', 'house'],
  'nastya muravyova': ['techno', 'trance'],
  'caiva': ['trance', 'techno'],
  'philippa pacho': ['hard techno', 'techno'],
  'spray': ['dubstep', 'uk bass'],
  'mary yuzovskaya': ['techno'],
  'stephanie sykes': ['techno', 'electro'],
  'batukizer': ['baile funk'],
  'tasha': ['jungle', 'drum and bass'],
  'ogazón': ['house', 'techno', 'electro'],
  'melanie havens': ['techno'],
  'felicie': ['techno'],
  'flo massé': ['house', 'disco'],
  'dr banana': ['uk garage', 'house', 'bassline'],
  'giammarco orsini': ['deep house', 'house'],
  'sylvie maziarz': ['hard techno', 'techno'],
  'dj spit': ['hard techno', 'gabber'],
  'isabella': ['hard techno', 'trance'],
  'mareena': ['techno'],
  'ocd': ['hard techno', 'techno'],
  'rosa pistola': ['dembow', 'reggaeton'],
  'paula tape': ['house', 'downtempo'],
  'luxe': ['house', 'uk garage'],
  'jordss': ['house', 'breakbeat'],
  'philipp strobel': ['techno', 'ebm'],
  'd33j': ['hip-hop', 'experimental'],
  'shinedoe': ['techno'],
  'iman omari': ['hip-hop', 'r&b', 'soul'],
  'total freedom': ['experimental', 'jersey club'],
  'gabber eleganza': ['gabber', 'hardcore'],
  'sven weisemann': ['deep house', 'dub techno'],
  'erol alkan': ['electro', 'house'],
  'italojohnson': ['house', 'techno'],
  'michael klein': ['hard techno', 'techno'],
  'fred again..': ['house', 'uk garage'],
  'solomun': ['house', 'deep house'],
  'kaytranada': ['house', 'hip-hop', 'r&b'],
  'brutalismus 3000': ['hard techno', 'gabber'],
  'stephan bodzin': ['techno'],
  'david august': ['downtempo', 'house'],
  'nightmares on wax': ['downtempo', 'trip-hop'],
  'pinkpantheress': ['uk garage', 'breakbeat'],
  'miss monique': ['progressive house', 'house'],
  'polo': ['nu-disco', 'downtempo'],
  'yaeji': ['house', 'hip-hop'],
  'horsegiirl': ['house'],
  'tale of us': ['techno'],
  'nikolina': ['hard techno', 'trance'],
  'motor city drum ensemble': ['deep house', 'house'],
  'adam beyer': ['techno'],
  'indira paganotto': ['psytrance', 'hard techno'],
  'egyptian lover': ['electro'],
  'lee ann roberts': ['hard techno', 'techno'],
  'dbn gogo': ['amapiano'],
  'gerd janson': ['house', 'disco'],
  'ben klock': ['techno', 'hard techno'],
  'breakbot': ['nu-disco', 'disco'],
  'blond:ish': ['house', 'tech house'],
  'kampire': ['singeli', 'uk bass'],
  'joe kay': ['r&b', 'hip-hop', 'soul'],
  'the martinez brothers': ['house', 'tech house'],
  'floating points': ['house', 'deep house', 'jazz'],
  'clara cuvé': ['hard techno', 'techno', 'electro'],
  'hunee': ['house', 'disco'],
  'oscar mulero': ['techno', 'hard techno'],
  'david vunk': ['italo disco', 'electro'],
  'cassie raptor': ['hard techno', 'acid'],
  'skepta': ['grime'],
  'jammer': ['grime'],
  'sasha': ['progressive house', 'trance'],
  'ross from friends': ['house', 'deep house'],
  'octave one': ['techno'],
  'sam gellaitry': ['hip-hop', 'experimental'],
  'miss kittin': ['electro', 'techno'],
  'henrik schwarz': ['house', 'deep house'],
  'hot since 82': ['tech house', 'house'],
  'alix perez': ['drum and bass', 'dubstep'],
  'james zabiela': ['tech house', 'breakbeat', 'techno'],
  'kelly lee owens': ['techno', 'synth-pop'],
  'richy ahmed': ['tech house', 'house'],
  'buraka som sistema': ['kuduro'],
  'luciano': ['minimal', 'tech house'],
  'tdj': ['trance', 'hard techno'],
  'diffrent': ['drum and bass'],
  'dengue dengue dengue': ['dembow', 'experimental'],
  'araabmuzik': ['hip-hop'],
  'sadar bahar': ['disco', 'soul'],
  'legowelt': ['electro', 'house', 'acid'],
  'dop': ['house', 'minimal'],
  'lokier': ['ebm', 'electro', 'industrial'],
  'daedelus': ['hip-hop', 'experimental'],
  'catnapp': ['drum and bass', 'breakbeat'],
  'somewhen': ['dub techno', 'hypnotic techno', 'techno'],
  'rossi.': ['house', 'tech house'],
  'louisahhh!!!': ['techno', 'ebm'],
  'silva bumpa': ['uk garage', 'bassline'],
  'panteros666': ['electro', 'jersey club'],
  'dj spanish fly': ['hip-hop'],
  'theo parrish': ['deep house', 'house'],
  'sef kombo': ['afro house', 'house'],
  'maedon': ['ebm', 'industrial', 'techno'],
  'louise chen': ['house', 'disco'],
  'dennis ferrer': ['house', 'deep house'],
  'daisybelle': ['new wave', 'synth-pop'],
  'zag erlat': ['disco', 'house'],
  'under black helmet': ['hard techno', 'ebm'],
  'francesco tristano': ['techno', 'experimental'],
  'spekki webu': ['trance', 'ambient'],
  'ela minus': ['synth-pop', 'experimental'],
  'tiffany calver': ['hip-hop'],
  'd. tiffany': ['house', 'breakbeat', 'trance'],
  'doc martin': ['house', 'deep house'],
  'kwartz': ['techno', 'hard techno'],
  'vanyfox': ['kuduro'],
  'lord apex': ['hip-hop'],
  'yha yha': ['hard techno', 'gabber'],
  'ayarcana': ['techno', 'ebm'],
  'brame': ['house'],
  'eli': ['progressive house', 'house'],
  'toro y moi': ['downtempo', 'funk'],
  'takuya nakamura': ['jazz', 'house'],
  'brutalismus': ['hard techno', 'gabber'],
  'malugi': ['house', 'hard techno', 'breakbeat'],
  'lady shaka': ['dancehall', 'jersey club'],
  'didi han': ['house', 'tech house'],
  'séxstasy': ['reggaeton', 'dembow'],
  'istanbul ghetto club': ['ghetto house', 'electro'],
  'mindmistake': ['hardcore', 'gabber'],
  'paolo ferrara': ['hard techno', 'techno'],

  // --- manual pass, batch 7 (Beatport / big-room / footwork / STVOL) ---
  'charlotte de witte': ['techno', 'hard techno'],
  'joseph capriati': ['techno'],
  'nicole moudaber': ['techno'],
  'chris liebing': ['techno', 'hard techno'],
  'luke slater': ['techno'],
  'paco osuna': ['techno', 'tech house'],
  'enzo siragusa': ['tech house', 'minimal'],
  'm.a.n.d.y.': ['house', 'tech house'],
  'gorgon city': ['house', 'uk garage'],
  'solardo': ['tech house', 'house'],
  'vintage culture': ['house', 'tech house'],
  'camelphat': ['house', 'tech house'],
  'pete tong': ['house'],
  'mk': ['house', 'deep house'],
  'lee foss': ['house', 'tech house'],
  'alan fitzpatrick': ['techno', 'tech house'],
  'anfisa letyago': ['techno'],
  'sara landry': ['hard techno', 'techno'],
  'barem': ['minimal', 'techno'],
  'axel boman': ['house', 'deep house'],
  'hannah laing': ['hard techno', 'techno', 'house'],
  'max dean': ['tech house', 'house'],
  'jaguar': ['house', 'breakbeat'],
  'sébastien léger': ['progressive house', 'house'],
  'fatboy slim': ['big beat', 'house'],
  'sg lewis': ['house', 'disco'],
  'shiba san': ['tech house', 'house'],
  'purple disco machine': ['nu-disco', 'house', 'disco'],
  'bart skils': ['techno'],
  'alienata': ['techno', 'electro', 'ebm'],
  'dj spinn': ['footwork', 'juke', 'drum and bass'],
  'traxman': ['footwork', 'juke'],
  'gene hunt': ['house', 'acid', 'deep house'],
  'dj manny': ['footwork', 'juke'],
  'zack fox': ['hip-hop'],
  'dj maria.': ['hard techno', 'trance'],
  'trancemaster krause': ['trance'],
  'a.g': ['grime'],
  'spooky': ['grime'],
  'grandmixxer': ['grime'],
  'cream soda': ['synth-pop', 'new wave'],
  'locked club': ['breakbeat', 'techno', 'hard techno'],
  'nocow': ['ambient', 'experimental', 'techno'],
  'wiki': ['hip-hop'],
  'bella boo': ['house', 'italo disco'],
  'house shoes': ['hip-hop'],

  // --- manual pass, batch 8 ------------------------------------------
  'pan-pot': ['techno'],
  'guy gerber': ['minimal', 'house'],
  'steve bug': ['tech house', 'minimal', 'house'],
  'robert hood': ['minimal', 'techno'],
  'danny daze': ['electro', 'techno'],
  'danny tenaglia': ['house', 'deep house'],
  'âme': ['deep house', 'house'],
  'michael mayer': ['house', 'techno'],
  'joey beltram': ['techno', 'acid'],
  'sonny fodera': ['house', 'tech house'],
  'franky rizardo': ['house', 'tech house'],
  'mochakk': ['house', 'tech house'],
  'rüfüs du sol': ['house', 'downtempo'],
  'sofi tukker': ['house'],
  'channel tres': ['house', 'hip-hop'],
  'ilario alicante': ['techno'],
  'rebolledo': ['italo disco', 'minimal'],
  'layla benitez': ['techno'],
  'anna': ['techno'],
  'sama abdulhadi': ['techno'],
  'michael bibi': ['tech house', 'house'],
  'chris stussy': ['house', 'tech house', 'minimal'],
  'sofia rodina': ['hard techno', 'techno'],
  'лауд': ['hip-hop'],
};
